name: CI/CD
on:
  pull_request:
    branches: [main]
jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache multiple paths
        uses: actions/cache@v2
        id: yarn-build-cache
        with:
          path: |
            node_modules
            build
          key:
            ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Install serve
        run: sudo npm i -g serve

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          REACT_APP_BASE_API_URL: ${{ secrets.API_URL }}
          REACT_APP_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        with:
          build: yarn build
          start: serve -s build -l 3000
          browser: chrome
          headless: true
          env: API_URL=http://api.exchangeratesapi.io/v1

      - name: Unit and integration tests
        run: yarn test
